name: Bulb Simulation

on:
  push:
    branches:
      - main

jobs:
  simulate_bulb:
    runs-on: windows-latest  # Use windows-latest for a Windows environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 

      - name: Run Bulb Simulation
        run: python i200685_MLOps_Demo1.ipynb
